Added Cylc Doc to Install Cylc Components
cylc/release-actions pull request #58
Opened 2023-10-04 14:16 UTC by wxtim

2023-10-04 15:28 UTC, MetRonnie requested changes

2023-10-04 15:28 UTC, MetRonnie commented on install-cylc-components/action.yml
> +        cylc_rose: ${{ inputs.cylc_doc_tag     || steps.get_tag.outputs.cylc_doc }}
```suggestion
        cylc_doc: ${{ inputs.cylc_doc_tag     || steps.get_tag.outputs.cylc_doc }}
```

2023-10-04 15:28 UTC, MetRonnie commented on install-cylc-components/action.yml
> +        if [[ ${{ inputs.cylc_rose }} == true ]]; then
```suggestion
        if [[ ${{ inputs.cylc_doc}} == true ]]; then
```

2023-10-04 16:01 UTC, MetRonnie approved these changes
Looks good, do you want to test it out in your fork of cylc-doc before merging?

2023-10-05 09:31 UTC, wxtim commented
> Looks good, do you want to test it out in your fork of cylc-doc before merging?

Unfortunately it looks a bit more complex that that - 

Checking out the right branch is simple - I used `cylc_doc_tag: ${{github.sha}}`. Then I realized that I needed to at least check out `./docs/.github/actions/install-dependencies` to install the deps Pip cannot handle. Having done that, I got this problem - any thoughts ; https://github.com/wxtim/cylc-doc/actions/runs/6417167750/job/17422350311

2023-10-05 09:44 UTC, MetRonnie commented
> Checking out the right branch is simple - I used `cylc_doc_tag: ${{github.sha}}`

I don't think that's right. The point of this is you don't specify the `cylc_doc_tag` - it is automatically selected

2023-10-05 10:45 UTC, wxtim commented
> > Checking out the right branch is simple - I used `cylc_doc_tag: ${{github.sha}}`
> 
> I don't think that's right. The point of this is you don't specify the `cylc_doc_tag` - it is automatically selected

Won't it automatically specify the latest version, not the branch under test

2023-10-05 13:03 UTC, wxtim commented
> > Checking out the right branch is simple - I used `cylc_doc_tag: ${{github.sha}}`
> 
> I don't think that's right. The point of this is you don't specify the `cylc_doc_tag` - it is automatically selected

Agreed - my mistake

I can't get mine to go past the git rebase step, but I think that the critical parts work https://github.com/wxtim/cylc-doc/actions/runs/6418414801/job/17426157554

2023-10-10 13:57 UTC, MetRonnie commented
That could be because your `gh-pages` branch on your fork is quite far behind the main repo?

2023-10-10 13:58 UTC, wxtim commented
> That could be because your `gh-pages` branch on your fork is quite far behind the main repo?

I thought that I'd synced it

2023-10-10 14:04 UTC, MetRonnie commented
![image](https://github.com/cylc/release-actions/assets/61982285/c1a15312-2673-4d32-9cfb-d617320d1612)

2023-10-12 10:03 UTC, wxtim commented
@MetRonnie  - I think GH has decided that I'm bitcoin mining - none of my workflows are running!

2023-10-17 15:22 UTC, MetRonnie commented
What's the status with this? Did you successfully test it out?

2023-10-17 15:49 UTC, wxtim commented
> What's the status with this? Did you successfully test it out?

I'll try again...

2023-10-17 16:53 UTC, MetRonnie commented
> I'm also not sure that the nightly build isn't mostly working now.

Come again?

2023-10-18 07:44 UTC, wxtim commented
> > I'm also not sure that the nightly build isn't mostly working now.
> 
> Come again?
> 
> Even if nightly is passing, we know it's always building from master even when it's supposed to be 8.

Ah. Forgot that bit.

2023-10-23 10:32 UTC, wxtim commented
Looks like it's partially working on https://github.com/wxtim/cylc-doc/actions/runs/6611755158/job/17956303415 - although I'm not sure about the error on 8.2.x branches - I've reproduced something like this locally.

2023-10-25 11:50 UTC, MetRonnie commented
> Looks like it's partially working on https://github.com/wxtim/cylc-doc/actions/runs/6611755158/job/17956303415 - although I'm not sure about the error on 8.2.x branches - I've reproduced something like this locally.

`ERROR: An option to autoclass is either unknown or has an invalid value: 'no-index'`

Your cylc-doc nightly workflow is still checking out master - it needs to check out the branch as determined by this action

2023-10-25 12:33 UTC, wxtim commented
> Your cylc-doc nightly workflow is still checking out master - it needs to check out the branch as determined by this action

The trouble here is that we need to run `cylc-doc:.github/actions/install-dependencies` to allow the Cylc component to install properly. I think that I've successfully bodged a demo in https://github.com/wxtim/cylc-doc/actions/runs/6640353536/job/18040602680 which shows this change working correctly, but I'm not sure if we can use it without moving `install-dependencies` (it's Pygraphviz again) to another repo?

2023-10-25 13:08 UTC, MetRonnie commented
Can we not just run `actions/checkout` twice: once at the beginning to checkout master, then once after this action has run to checkout the correct branch?

2023-10-27 08:43 UTC, wxtim commented
Finally https://github.com/wxtim/cylc-doc/actions/runs/6664794951/job/18113098974

I think that the 8.2-jps-V1 is broken for other reasons.

2023-11-02 11:11 UTC, closed without merging